type Release = {
    title: string;
    type: "Album" | "EP" | "Single" | "Remix";
    genres: string[];
    artists: string[];
    date: string;
    cover: string;
    link: string;
    counts?: number;
}

/**
 * Probably doesn't have to do some fancy fetching from YouTube or SoundCloud
 * or whatever because I probably won't be releasing music that often lmao
 */
export const discography: Release[] = [
    {
        title: "hi",
        artists: ["Azur1s"],
        type: "Album",
        genres: ["UKG", "House", "Rawstyle", "Tearout", "Amapiano", "Jerk"],
        date: "2025-01-07",
        cover: "/images/discography/hi.png",
        link: "https://www.youtube.com/watch?v=vMbKmhW5YVQ",
        counts: 9,
    },
    {
        title: "FE!N (Azur1s Remix)",
        artists: ["Travis Scott"],
        type: "Remix",
        genres: ["UKG"],
        date: "2024-12-18",
        cover: "/images/discography/fein remix.png",
        link: "https://www.youtube.com/watch?v=JUYsNNVRig4",
    },
    {
        title: "doomed toxic yuri?",
        artists: ["Azur1s"],
        type: "Single",
        genres: ["UKG"],
        date: "2024-12-12",
        cover: "/images/discography/doomed toxic yuri.jpg",
        link: "https://www.youtube.com/watch?v=o9qOMqRrHmE",
    },
    {
        title: "smut yuri",
        artists: ["Azur1s"],
        type: "Single",
        genres: ["UKG"],
        date: "2024-10-1",
        cover: "/images/discography/smut yuri.jpg",
        link: "https://www.youtube.com/watch?v=A1QKcGUOrLY",
    },
    {
        title: "what's the point of anything if there aren't any lesbians",
        artists: ["Azur1s"],
        type: "Single",
        genres: ["Tearout", "House"],
        date: "2024-09-20",
        cover: "/images/discography/wtpoaitaal.jpg",
        link: "https://www.youtube.com/watch?v=A1QKcGUOrLY",
    },
    {
        title: "show me (who you are)",
        artists: ["Azur1s", "Glitch Cat"],
        type: "Single",
        genres: ["Future Bass"],
        date: "2024-08-06",
        cover: "/images/discography/show me who you are.jpg",
        link: "https://soundcloud.com/azur1s/show-me",
    },
    {
        title: "photobomb VIP",
        artists: ["Azur1s", "Glitch Cat"],
        type: "Single",
        genres: ["Baile Funk", "House"],
        date: "2024-08-06",
        cover: "/images/discography/photobomb vip.jpg",
        link: "https://www.youtube.com/watch?v=hCQ9SNVVw_E",
    },
    {
        title: "photobomb",
        artists: ["Glitch Cat", "Azur1s"],
        type: "Single",
        genres: ["Future Bass", "Future Riddim", "Jersey", "Baile Funk"],
        date: "2024-08-06",
        cover: "/images/discography/photobomb.jpg",
        link: "https://www.youtube.com/watch?v=o28XHdXQ7a4 ",
    },
    {
        title: "asdfghjkl,a",
        artists: ["Azur1s"],
        type: "Single",
        genres: ["UKG", "House"],
        date: "2024-07-07",
        cover: "/images/discography/asdfghjkl,,a.jpg",
        link: "https://www.youtube.com/watch?v=kpsYZ-Zga4w",
    },
    {
        title: "Granduer Wander",
        artists: ["Azur1s"],
        type: "Album",
        genres: ["House"],
        date: "2024-06-10",
        cover: "/images/discography/granduer wander.jpg",
        link: "https://www.youtube.com/watch?v=kpsYZ-Zga4w",
        counts: 5,
    },
    {
        title: "Never Knew You",
        artists: ["Azur1s"],
        type: "Single",
        genres: ["Rawstyle"],
        date: "2024-05-22",
        cover: "/images/discography/never knew you.jpg",
        link: "https://www.youtube.com/watch?v=pVUmG6qHlG8",
    },
    {
        title: "Waiting For You",
        artists: ["Azur1s"],
        type: "Single",
        genres: ["Tearout"],
        date: "2024-05-20",
        cover: "/images/discography/waiting for you.jpg",
        link: "https://www.youtube.com/watch?v=pVUmG6qHlG8",
    },
    {
        title: "Real Love",
        artists: ["Azur1s"],
        type: "Single",
        genres: ["Rawstyle"],
        date: "2024-05-13",
        cover: "/images/discography/real love.jpg",
        link: "https://www.youtube.com/watch?v=aszAPdTCMxk",
    },
    {
        title: "Achromatic",
        artists: ["Azur1s"],
        type: "Single",
        genres: ["Rawstyle"],
        date: "2024-05-11",
        cover: "/images/discography/achromatic.jpg",
        link: "https://www.youtube.com/watch?v=aszAPdTCMxk",
    },
    {
        title: "Losing Myself",
        artists: ["Azur1s"],
        type: "Single",
        genres: ["Rawstyle"],
        date: "2024-04-24",
        cover: "/images/discography/losing myself.jpg",
        link: "https://www.youtube.com/watch?v=xyaeOFSlo7c",
    },
    {
        title: "Love Addict",
        artists: ["Azur1s"],
        type: "Single",
        genres: ["Rawstyle"],
        date: "2024-04-07",
        cover: "/images/discography/love addict.jpg",
        link: "https://www.youtube.com/watch?v=A5Vxpftn5Qg",
    },
    {
        title: "Elysian's Fantasia",
        artists: ["Azur1s"],
        type: "Single",
        genres: ["Jersey"],
        date: "2024-03-22",
        cover: "/images/discography/elysians fantasia.jpg",
        link: "https://www.youtube.com/watch?v=U7tE_rCPa0c",
    },
    {
        title: "gothgriddygirlygrippystickysockgirl",
        artists: ["Azur1s"],
        type: "Single",
        genres: ["Hybrid Trap", "Future Riddim", "Psytrance", "Jersey", "Drum and Bass", "Uptempo", "Rawstyle"],
        date: "2024-03-04",
        cover: "/images/discography/ggggssg.jpg",
        link: "https://www.youtube.com/watch?v=1srxZn-GYyY",
    },
    {
        title: "Caera (VIP)",
        artists: ["Azur1s"],
        type: "Single",
        genres: ["House"],
        date: "2024-02-09",
        cover: "/images/discography/caera vip.jpg",
        link: "https://www.youtube.com/watch?v=7vtzbAgEVGQ",
    },
    {
        title: "Tonal3 x Fierce (House VIP)",
        artists: ["Azur1s"],
        type: "Single",
        genres: ["House"],
        date: "2024-01-30",
        cover: "/images/discography/tonal3 x fierce.jpg",
        link: "https://www.youtube.com/watch?v=iVdxAHqNX7U",
    },
    {
        title: "Don't Fall In Love",
        artists: ["Azur1s"],
        type: "Single",
        genres: ["Jersey"],
        date: "2024-01-26",
        cover: "/images/discography/dont fall in love.jpg",
        link: "https://www.youtube.com/watch?v=acxTNMEnhLI",
    },
    {
        title: "yanderegrippysockgirl",
        artists: ["Azur1s"],
        type: "Single",
        genres: ["Riddim"],
        date: "2024-01-26",
        cover: "/images/discography/ygsg.jpg",
        link: "https://www.youtube.com/watch?v=Y8Swmq13Rgo",
    },

    {
        title: "Without You Beside Me",
        artists: ["Azur1s", "Slainix"],
        type: "Single",
        genres: ["Dubstep"],
        date: "2023-12-02",
        cover: "/images/discography/ygsg.jpg",
        link: "https://www.youtube.com/watch?v=3BFVXfL0zZs",
    },
    {
        title: "Take Me Higher",
        artists: ["Azur1s", "UTAGE"],
        type: "Single",
        genres: ["Drum and Bass"],
        date: "2023-10-28",
        cover: "/images/discography/ygsg.jpg",
        link: "https://www.youtube.com/watch?v=y3I2luhM-9A",
    },
    {
        title: "Caera",
        artists: ["Azur1s"],
        type: "Single",
        genres: ["Drum and Bass"],
        date: "2023-10-1",
        cover: "/images/discography/ygsg.jpg",
        link: "https://www.youtube.com/watch?v=pqr7KP9pjQ0",
    },
    {
        title: "High",
        artists: ["Azur1s"],
        type: "Single",
        genres: ["Slap House"],
        date: "2023-9-21",
        cover: "/images/discography/ygsg.jpg",
        link: "https://www.youtube.com/watch?v=C6s-EzI_Vng",
    },
    {
        title: "Expansion",
        artists: ["Azur1s"],
        type: "Album",
        genres: ["Jersey", "Baile Funk", "Midtempo", "Hardstyle", "Drum and Bass", "Dubstep"],
        date: "2023-10-28",
        cover: "/images/discography/ygsg.jpg",
        link: "https://www.youtube.com/watch?v=8IOHpk-JFOc",
        counts: 6,
    },
    {
        title: "Tonal3",
        artists: ["Azur1s"],
        type: "Single",
        genres: ["Electro House"],
        date: "2023-7-23",
        cover: "/images/discography/ygsg.jpg",
        link: "https://www.youtube.com/watch?v=V2xS3PMYOcU",
    },
    {
        title: "Tears Out",
        artists: ["Azur1s"],
        type: "Single",
        genres: ["Tearout"],
        date: "2023-5-27",
        cover: "/images/discography/ygsg.jpg",
        link: "https://www.youtube.com/watch?v=pwLFrBN3O30",
    },
    {
        title: "One More Night",
        artists: ["Azur1s"],
        type: "Single",
        genres: ["Color House"],
        date: "2023-5-22",
        cover: "/images/discography/ygsg.jpg",
        link: "https://www.youtube.com/watch?v=l3COOdRM9TM",
    },
    {
        title: "The Remains",
        artists: ["Azur1s"],
        type: "Single",
        genres: ["Color Bass"],
        date: "2023-5-20",
        cover: "/images/discography/ygsg.jpg",
        link: "https://www.youtube.com/watch?v=-6embqfaXu8",
    },
    {
        title: "Hydrangea",
        artists: ["Azur1s"],
        type: "Single",
        genres: ["Color House"],
        date: "2023-4-9",
        cover: "/images/discography/ygsg.jpg",
        link: "https://www.youtube.com/watch?v=32VOamhHM5I",
    },
    {
        title: "Skida",
        artists: ["Azur1s"],
        type: "Single",
        genres: ["Midtempo"],
        date: "2023-4-9",
        cover: "/images/discography/ygsg.jpg",
        link: "https://www.youtube.com/watch?v=DmmXAsxbLzQ",
    },
    {
        title: "Sky Light",
        artists: ["Azur1s"],
        type: "Single",
        genres: ["Color House"],
        date: "2023-4-9",
        cover: "/images/discography/ygsg.jpg",
        link: "https://www.youtube.com/watch?v=RWxu5q6t408",
    },
];