/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Background: typeof import('./src/components/Background.vue')['default']
    Button: typeof import('./src/components/Button.vue')['default']
    CoolText: typeof import('./src/components/CoolText.vue')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    ICarbonAccessibility: typeof import('~icons/carbon/accessibility')['default']
    ICarbonAsleepFilled: typeof import('~icons/carbon/asleep-filled')['default']
    ICarbonAssembly: typeof import('~icons/carbon/assembly')['default']
    ICarbonAssmebly: typeof import('~icons/carbon/assmebly')['default']
    IconLink: typeof import('./src/components/IconLink.vue')['default']
    IFluencyMoon: typeof import('~icons/fluency/moon')['default']
    'IMdi-{{': typeof import('~icons/mdi/{{')['default']
    IMdiAccount: typeof import('~icons/mdi/account')['default']
    IMdiAllo: typeof import('~icons/mdi/allo')['default']
    IMdiCopyright: typeof import('~icons/mdi/copyright')['default']
    IMdiFolderOpen: typeof import('~icons/mdi/folder-open')['default']
    IMdiGithub: typeof import('~icons/mdi/github')['default']
    IMdiGithubFace: typeof import('~icons/mdi/github-face')['default']
    IMdiLightbulbOn: typeof import('~icons/mdi/lightbulb-on')['default']
    IMdiMoonWaningCrescent: typeof import('~icons/mdi/moon-waning-crescent')['default']
    IMdiSoundcloud: typeof import('~icons/mdi/soundcloud')['default']
    IMdiSpinner: typeof import('~icons/mdi/spinner')['default']
    IMdiSpotify: typeof import('~icons/mdi/spotify')['default']
    IMdiYoutube: typeof import('~icons/mdi/youtube')['default']
    'IMi:moon': typeof import('~icons/mi/moon')['default']
    NavBar: typeof import('./src/components/NavBar.vue')['default']
    Project: typeof import('./src/components/Project.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Title: typeof import('./src/components/Title.vue')['default']
  }
}
